# -*- coding: utf-8 -*-
"""analysis_utils (con explicaciones).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_aT82sOnJLvKOlhngM_K1SW1CglonXGW
"""

# =============================================================================
# MÓDULO DE ANÁLISIS AVANZADO (ANALYSIS UTILS)
# =============================================================================

import pandas as pd
import numpy as np
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass
from enum import Enum


# =============================================================================
# CONFIGURACIÓN DE UMBRALES Y SEVERIDAD
# =============================================================================

class SeveridadAlerta(Enum):
    """Niveles de severidad para las alertas"""
    CRITICO = "🚨"
    ADVERTENCIA = "⚠️"
    INFO = "ℹ️"
    POSITIVO = "✅"


@dataclass
class UmbralHabito:
    """Definición de umbrales para cada tipo de hábito"""
    nombre: str
    minimo_saludable: Optional[float] = None
    maximo_saludable: Optional[float] = None
    optimo: Optional[float] = None
    unidad: str = ""


# Diccionario de umbrales recomendados (basado en evidencia científica)
UMBRALES_DEFAULT = {
    # Sueño
    'sueño': UmbralHabito('Sueño', minimo_saludable=7, maximo_saludable=9, optimo=8, unidad='horas'),
    'sleep': UmbralHabito('Sleep', minimo_saludable=7, maximo_saludable=9, optimo=8, unidad='hours'),

    # Ejercicio
    'ejercicio': UmbralHabito('Ejercicio', minimo_saludable=30, optimo=60, unidad='min'),
    'exercise': UmbralHabito('Exercise', minimo_saludable=30, optimo=60, unidad='min'),
    'pasos': UmbralHabito('Pasos', minimo_saludable=7000, optimo=10000, unidad='pasos'),
    'steps': UmbralHabito('Steps', minimo_saludable=7000, optimo=10000, unidad='steps'),

    # Estudio/Trabajo
    'estudio': UmbralHabito('Estudio', maximo_saludable=8, optimo=6, unidad='horas'),
    'study': UmbralHabito('Study', maximo_saludable=8, optimo=6, unidad='hours'),
    'trabajo': UmbralHabito('Trabajo', maximo_saludable=9, optimo=8, unidad='horas'),
    'work': UmbralHabito('Work', maximo_saludable=9, optimo=8, unidad='hours'),

    # Hidratación
    'agua': UmbralHabito('Agua', minimo_saludable=6, optimo=8, unidad='vasos'),
    'water': UmbralHabito('Water', minimo_saludable=6, optimo=8, unidad='glasses'),

    # Alimentación
    'calorias': UmbralHabito('Calorías', minimo_saludable=1500, maximo_saludable=2500, optimo=2000, unidad='kcal'),
    'calories': UmbralHabito('Calories', minimo_saludable=1500, maximo_saludable=2500, optimo=2000, unidad='kcal'),

    # Pantallas
    'pantalla': UmbralHabito('Tiempo de pantalla', maximo_saludable=4, optimo=2, unidad='horas'),
    'screen': UmbralHabito('Screen time', maximo_saludable=4, optimo=2, unidad='hours'),

    # Hábitos negativos
    'cigarrillos': UmbralHabito('Cigarrillos', maximo_saludable=0, optimo=0, unidad='unidades'),
    'cigarettes': UmbralHabito('Cigarettes', maximo_saludable=0, optimo=0, unidad='units'),
    'alcohol': UmbralHabito('Alcohol', maximo_saludable=1, optimo=0, unidad='bebidas'),
}


# =============================================================================
# DETECCIÓN AUTOMÁTICA DE HÁBITOS
# =============================================================================

def _detectar_habito(nombre_columna: str) -> Optional[UmbralHabito]:
    """
    Detecta automáticamente qué tipo de hábito es una columna.

    Args:
        nombre_columna: Nombre de la columna del DataFrame

    Returns:
        UmbralHabito si se detecta, None si no se reconoce
    """
    nombre_lower = nombre_columna.lower()

    # Buscar coincidencias en los umbrales definidos
    for clave, umbral in UMBRALES_DEFAULT.items():
        if clave in nombre_lower:
            return umbral

    return None


# =============================================================================
# ANÁLISIS DE TENDENCIAS
# =============================================================================

def calcular_tendencia(serie: pd.Series) -> Tuple[str, float]:
    """
    Calcula la tendencia de una serie temporal usando regresión lineal simple.

    Args:
        serie: Serie de pandas con valores numéricos

    Returns:
        Tupla con (dirección, pendiente) donde dirección es 'subiendo', 'bajando' o 'estable'
    """
    # Eliminar NaN y verificar que hay suficientes datos
    serie_limpia = serie.dropna()

    if len(serie_limpia) < 3:
        return 'insuficiente', 0.0

    # Crear índices numéricos para la regresión
    x = np.arange(len(serie_limpia))
    y = serie_limpia.values

    # Calcular pendiente usando mínimos cuadrados
    pendiente = np.polyfit(x, y, 1)[0]

    # Clasificar la tendencia
    if abs(pendiente) < 0.1:  # Cambio menor al 10% del rango
        direccion = 'estable'
    elif pendiente > 0:
        direccion = 'subiendo'
    else:
        direccion = 'bajando'

    return direccion, pendiente


# =============================================================================
# DETECCIÓN DE ANOMALÍAS
# =============================================================================

def detectar_anomalias(serie: pd.Series, umbral_zscore: float = 2.5) -> List[Tuple[int, float]]:
    """
    Detecta valores atípicos usando Z-score.

    Args:
        serie: Serie de pandas con valores numéricos
        umbral_zscore: Número de desviaciones estándar para considerar anomalía

    Returns:
        Lista de tuplas (índice, valor) de los valores anómalos
    """
    serie_limpia = serie.dropna()

    if len(serie_limpia) < 5:
        return []

    # Calcular Z-scores
    media = serie_limpia.mean()
    std = serie_limpia.std()

    if std == 0:
        return []

    z_scores = np.abs((serie_limpia - media) / std)

    # Detectar anomalías
    anomalias = []
    for idx, z_score in zip(serie_limpia.index, z_scores):
        if z_score > umbral_zscore:
            anomalias.append((idx, serie[idx]))

    return anomalias


# =============================================================================
# GENERACIÓN INTELIGENTE DE ALERTAS
# =============================================================================

@dataclass
class Alerta:
    """Estructura para almacenar alertas con metadata"""
    severidad: SeveridadAlerta
    titulo: str
    mensaje: str
    metrica: float
    umbral: Optional[float] = None
    tendencia: Optional[str] = None


def generar_alertas_inteligentes(
    df: pd.DataFrame,
    umbrales_personalizados: Optional[Dict[str, UmbralHabito]] = None,
    incluir_tendencias: bool = True,
    incluir_anomalias: bool = True
) -> List[Alerta]:
    """
    Genera alertas inteligentes basadas en análisis de hábitos.

    Args:
        df: DataFrame con datos de hábitos (debe tener columna de fecha)
        umbrales_personalizados: Diccionario con umbrales custom (opcional)
        incluir_tendencias: Si True, analiza tendencias temporales
        incluir_anomalias: Si True, detecta días atípicos

    Returns:
        Lista de alertas ordenadas por severidad
    """
    alertas = []
    umbrales = umbrales_personalizados or UMBRALES_DEFAULT

    # Analizar cada columna numérica
    for columna in df.select_dtypes(include=[np.number]).columns:
        umbral = _detectar_habito(columna)

        if umbral is None:
            continue  # No es un hábito conocido

        serie = df[columna]
        media = serie.mean()

        # ========== ANÁLISIS DE PROMEDIOS ==========

        # Verificar mínimo saludable
        if umbral.minimo_saludable and media < umbral.minimo_saludable:
            severidad = SeveridadAlerta.CRITICO if media < umbral.minimo_saludable * 0.8 else SeveridadAlerta.ADVERTENCIA
            alertas.append(Alerta(
                severidad=severidad,
                titulo=f"{umbral.nombre} insuficiente",
                mensaje=f"Tu promedio es {media:.1f} {umbral.unidad}, pero se recomienda al menos {umbral.minimo_saludable} {umbral.unidad}.",
                metrica=media,
                umbral=umbral.minimo_saludable
            ))

        # Verificar máximo saludable
        if umbral.maximo_saludable and media > umbral.maximo_saludable:
            severidad = SeveridadAlerta.CRITICO if media > umbral.maximo_saludable * 1.2 else SeveridadAlerta.ADVERTENCIA
            alertas.append(Alerta(
                severidad=severidad,
                titulo=f"{umbral.nombre} excesivo",
                mensaje=f"Tu promedio es {media:.1f} {umbral.unidad}, pero se recomienda máximo {umbral.maximo_saludable} {umbral.unidad}.",
                metrica=media,
                umbral=umbral.maximo_saludable
            ))

        # Verificar si está en rango óptimo
        if umbral.optimo:
            diferencia = abs(media - umbral.optimo)
            if diferencia < umbral.optimo * 0.1:  # Dentro del 10% del óptimo
                alertas.append(Alerta(
                    severidad=SeveridadAlerta.POSITIVO,
                    titulo=f"¡Excelente {umbral.nombre}!",
                    mensaje=f"Tu promedio de {media:.1f} {umbral.unidad} está muy cerca del óptimo ({umbral.optimo} {umbral.unidad}).",
                    metrica=media,
                    umbral=umbral.optimo
                ))

        # ========== ANÁLISIS DE TENDENCIAS ==========

        if incluir_tendencias and len(serie) >= 7:
            tendencia, pendiente = calcular_tendencia(serie)

            # Alertas de tendencias preocupantes
            if tendencia == 'bajando' and umbral.minimo_saludable:
                if media < umbral.minimo_saludable * 1.2:  # Cerca del límite y bajando
                    alertas.append(Alerta(
                        severidad=SeveridadAlerta.ADVERTENCIA,
                        titulo=f"Tendencia decreciente en {umbral.nombre}",
                        mensaje=f"Tu {umbral.nombre} está disminuyendo. Promedio actual: {media:.1f} {umbral.unidad}.",
                        metrica=media,
                        tendencia='bajando'
                    ))

            elif tendencia == 'subiendo' and umbral.maximo_saludable:
                if media > umbral.maximo_saludable * 0.8:  # Cerca del límite y subiendo
                    alertas.append(Alerta(
                        severidad=SeveridadAlerta.ADVERTENCIA,
                        titulo=f"Tendencia creciente en {umbral.nombre}",
                        mensaje=f"Tu {umbral.nombre} está aumentando. Promedio actual: {media:.1f} {umbral.unidad}.",
                        metrica=media,
                        tendencia='subiendo'
                    ))

            # Alertas de mejoras
            elif tendencia == 'subiendo' and umbral.minimo_saludable:
                if media > umbral.minimo_saludable:
                    alertas.append(Alerta(
                        severidad=SeveridadAlerta.POSITIVO,
                        titulo=f"¡Mejorando en {umbral.nombre}!",
                        mensaje=f"Tu {umbral.nombre} está aumentando consistentemente. ¡Sigue así!",
                        metrica=media,
                        tendencia='subiendo'
                    ))

        # ========== DETECCIÓN DE ANOMALÍAS ==========

        if incluir_anomalias:
            anomalias = detectar_anomalias(serie)

            if len(anomalias) > 0:
                # Solo alertar si hay más de 2 anomalías
                if len(anomalias) > 2:
                    alertas.append(Alerta(
                        severidad=SeveridadAlerta.INFO,
                        titulo=f"Días atípicos en {umbral.nombre}",
                        mensaje=f"Se detectaron {len(anomalias)} días con valores inusuales en {umbral.nombre}.",
                        metrica=len(anomalias)
                    ))

    # Ordenar por severidad (Crítico > Advertencia > Info > Positivo)
    orden_severidad = {
        SeveridadAlerta.CRITICO: 0,
        SeveridadAlerta.ADVERTENCIA: 1,
        SeveridadAlerta.INFO: 2,
        SeveridadAlerta.POSITIVO: 3
    }

    alertas_ordenadas = sorted(alertas, key=lambda x: orden_severidad[x.severidad])

    return alertas_ordenadas


def generar_alertas(df: pd.DataFrame) -> List[str]:
    """
    Función simplificada compatible con tu código anterior.
    Mantiene la misma interfaz pero usa el motor mejorado internamente.

    Args:
        df: DataFrame con datos de hábitos

    Returns:
        Lista de strings con mensajes de alerta
    """
    alertas_obj = generar_alertas_inteligentes(df)

    # Convertir objetos Alerta a strings simples
    mensajes = []
    for alerta in alertas_obj:
        mensaje = f"{alerta.severidad.value} {alerta.titulo}: {alerta.mensaje}"
        mensajes.append(mensaje)

    return mensajes


# =============================================================================
# ANÁLISIS DE CORRELACIONES
# =============================================================================

def analizar_correlaciones(
    df: pd.DataFrame,
    umbral_correlacion: float = 0.5
) -> List[Tuple[str, str, float]]:
    """
    Encuentra correlaciones significativas entre hábitos.

    Args:
        df: DataFrame con datos de hábitos
        umbral_correlacion: Valor mínimo de correlación para reportar

    Returns:
        Lista de tuplas (habito1, habito2, correlacion)
    """
    # Seleccionar solo columnas numéricas
    df_numerico = df.select_dtypes(include=[np.number])

    if len(df_numerico.columns) < 2:
        return []

    # Calcular matriz de correlación
    corr_matrix = df_numerico.corr()

    # Encontrar correlaciones significativas
    correlaciones = []
    for i in range(len(corr_matrix.columns)):
        for j in range(i + 1, len(corr_matrix.columns)):
            corr_valor = corr_matrix.iloc[i, j]

            if abs(corr_valor) >= umbral_correlacion:
                habito1 = corr_matrix.columns[i]
                habito2 = corr_matrix.columns[j]
                correlaciones.append((habito1, habito2, corr_valor))

    # Ordenar por magnitud de correlación
    correlaciones.sort(key=lambda x: abs(x[2]), reverse=True)

    return correlaciones


# =============================================================================
# RESUMEN ESTADÍSTICO MEJORADO
# =============================================================================

def resumen_avanzado(df: pd.DataFrame) -> pd.DataFrame:
    """
    Genera un resumen estadístico más completo que df.describe().

    Args:
        df: DataFrame con datos de hábitos

    Returns:
        DataFrame con estadísticas descriptivas mejoradas
    """
    df_numerico = df.select_dtypes(include=[np.number])

    if df_numerico.empty:
        return pd.DataFrame()

    resumen = pd.DataFrame({
        'Media': df_numerico.mean(),
        'Mediana': df_numerico.median(),
        'Desv_Std': df_numerico.std(),
        'Mínimo': df_numerico.min(),
        'Máximo': df_numerico.max(),
        'Rango': df_numerico.max() - df_numerico.min(),
        'CV_%': (df_numerico.std() / df_numerico.mean() * 100).round(1),  # Coeficiente de variación
        'Datos_Completos_%': ((df_numerico.count() / len(df_numerico)) * 100).round(1)
    }).round(2)

    return resumen


def resumen_basico(df: pd.DataFrame) -> pd.DataFrame:
    """
    Función legacy compatible con tu código anterior.
    """
    return df.describe().round(2)


# =============================================================================
# FUNCIÓN DE ANÁLISIS COMPLETO
# =============================================================================

def analisis_completo(df: pd.DataFrame) -> Dict:
    """
    Realiza un análisis completo de los hábitos y retorna todos los insights.

    Args:
        df: DataFrame con datos de hábitos

    Returns:
        Diccionario con todos los análisis
    """
    return {
        'alertas': generar_alertas_inteligentes(df),
        'resumen_estadistico': resumen_avanzado(df),
        'correlaciones': analizar_correlaciones(df),
        'total_dias': len(df),
        'columnas_analizadas': list(df.select_dtypes(include=[np.number]).columns)
    }
