# -*- coding: utf-8 -*-
"""app (con explicaciones) integracion en streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdBCMuDj_wq26NzLHNCvKJI8wKIZbtWX
"""

# =============================================================================
# APP STREAMLIT - ANALIZADOR DE HÁBITOS DIARIOS
# =============================================================================

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from io import StringIO, BytesIO

# Importar módulos personalizados
from data_utils import cargar_y_limpiar_datos
from analysis_utils import analisis_completo, SeveridadAlerta
from plot_utils import (
    generar_dashboard_completo,
    grafico_tendencias,
    grafico_correlaciones,
    grafico_radar_habitos,
    grafico_distribuciones
)

# =============================================================================
# CONFIGURACIÓN DE LA PÁGINA
# =============================================================================

st.set_page_config(
    page_title="Analizador de Hábitos Diarios",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =============================================================================
# CSS PERSONALIZADO PARA DISEÑO MODERNO
# =============================================================================

st.markdown("""
<style>
    /* Tema general */
    .main {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        background-attachment: fixed;
    }

    .stApp {
        background: transparent;
    }

    /* Contenedor principal con efecto glassmorphism */
    .block-container {
        background: rgba(255, 255, 255, 0.95);
        backdrop-filter: blur(10px);
        border-radius: 20px;
        padding: 2rem;
        box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
    }

    /* Título principal */
    h1 {
        color: #667eea;
        text-align: center;
        font-weight: 800;
        font-size: 3rem !important;
        text-shadow: 2px 2px 4px rgba(0,0,0,0.1);
        margin-bottom: 0.5rem;
    }

    /* Subtítulos */
    h2, h3 {
        color: #764ba2;
        font-weight: 600;
    }

    /* Tarjetas de métricas */
    div[data-testid="stMetricValue"] {
        font-size: 2rem;
        font-weight: 700;
        color: #667eea;
    }

    /* Botones */
    .stButton > button {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border: none;
        border-radius: 10px;
        padding: 0.5rem 2rem;
        font-weight: 600;
        transition: all 0.3s ease;
        box-shadow: 0 4px 15px 0 rgba(102, 126, 234, 0.4);
    }

    .stButton > button:hover {
        transform: translateY(-2px);
        box-shadow: 0 6px 20px 0 rgba(102, 126, 234, 0.6);
    }

    /* File uploader */
    .stFileUploader {
        background: rgba(102, 126, 234, 0.05);
        border-radius: 15px;
        padding: 1.5rem;
        border: 2px dashed #667eea;
    }

    /* Alertas personalizadas */
    .alerta-critica {
        background: linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 100%);
        color: white;
        padding: 1rem;
        border-radius: 10px;
        margin: 0.5rem 0;
        box-shadow: 0 4px 15px rgba(255, 107, 107, 0.3);
    }

    .alerta-advertencia {
        background: linear-gradient(135deg, #ffd93d 0%, #f6c23e 100%);
        color: #333;
        padding: 1rem;
        border-radius: 10px;
        margin: 0.5rem 0;
        box-shadow: 0 4px 15px rgba(255, 217, 61, 0.3);
    }

    .alerta-positiva {
        background: linear-gradient(135deg, #51cf66 0%, #37b24d 100%);
        color: white;
        padding: 1rem;
        border-radius: 10px;
        margin: 0.5rem 0;
        box-shadow: 0 4px 15px rgba(81, 207, 102, 0.3);
    }

    .alerta-info {
        background: linear-gradient(135deg, #4dabf7 0%, #228be6 100%);
        color: white;
        padding: 1rem;
        border-radius: 10px;
        margin: 0.5rem 0;
        box-shadow: 0 4px 15px rgba(77, 171, 247, 0.3);
    }

    /* Sidebar */
    section[data-testid="stSidebar"] {
        background: linear-gradient(180deg, #667eea 0%, #764ba2 100%);
    }

    section[data-testid="stSidebar"] * {
        color: white !important;
    }

    /* Dataframe */
    .dataframe {
        border-radius: 10px;
        overflow: hidden;
    }

    /* Animación de carga */
    @keyframes pulse {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.5; }
    }

    .loading {
        animation: pulse 1.5s ease-in-out infinite;
    }
</style>
""", unsafe_allow_html=True)

# =============================================================================
# FUNCIONES AUXILIARES
# =============================================================================

def guardar_archivo_temporal(uploaded_file):
    """Guarda el archivo subido temporalmente para procesarlo."""
    extension = uploaded_file.name.split('.')[-1].lower()
    temp_path = f"temp_file.{extension}"

    with open(temp_path, "wb") as f:
        f.write(uploaded_file.getbuffer())

    return temp_path


def mostrar_alerta(alerta):
    """Renderiza una alerta con estilo personalizado según su severidad."""
    if alerta.severidad == SeveridadAlerta.CRITICO:
        clase = "alerta-critica"
    elif alerta.severidad == SeveridadAlerta.ADVERTENCIA:
        clase = "alerta-advertencia"
    elif alerta.severidad == SeveridadAlerta.POSITIVO:
        clase = "alerta-positiva"
    else:
        clase = "alerta-info"

    st.markdown(f"""
    <div class="{clase}">
        <strong>{alerta.severidad.value} {alerta.titulo}</strong><br>
        {alerta.mensaje}
    </div>
    """, unsafe_allow_html=True)


# =============================================================================
# HEADER DE LA APLICACIÓN
# =============================================================================

st.markdown("<h1>📊 Analizador de Hábitos Diarios</h1>", unsafe_allow_html=True)

st.markdown("""
<div style='text-align: center; color: #666; margin-bottom: 2rem;'>
    <p style='font-size: 1.2rem;'>
        Transforma tus datos en <strong>insights accionables</strong> para mejorar tu vida diaria
    </p>
</div>
""", unsafe_allow_html=True)

# =============================================================================
# SIDEBAR - CONFIGURACIÓN E INSTRUCCIONES
# =============================================================================

with st.sidebar:
    st.markdown("## 🎯 Guía de Uso")

    with st.expander("📋 Requisitos del Archivo", expanded=True):
        st.markdown("""
        **⚠️ IMPORTANTE:**

        Antes de subir tu archivo, asegúrate de que:

        ✅ **Tiene una fila de encabezados clara** en la primera línea

        ✅ **Los nombres de columnas son descriptivos**:
        - ✨ Bueno: `fecha`, `sueño_horas`, `ejercicio_min`
        - ❌ Malo: `col1`, `x`, `datos`

        ✅ **Incluye una columna de fecha** (opcional pero recomendado)

        ✅ **Los datos son numéricos** para hábitos medibles

        ✅ **Formatos aceptados**: CSV, Excel (.xlsx), Word (.docx)
        """)

    with st.expander("📊 Hábitos Detectados Automáticamente"):
        st.markdown("""
        La app reconoce automáticamente:

        **Hábitos Positivos** (verde):
        - Sueño, Ejercicio, Agua, Pasos
        - Productividad, Estudio

        **Hábitos Negativos** (rojo):
        - Cigarrillos, Alcohol
        - Tiempo de pantalla excesivo

        **Métricas Continuas** (azul):
        - Peso, IMC, Presión arterial
        - Temperatura, Glucosa
        """)

    with st.expander("🎨 Visualizaciones Incluidas"):
        st.markdown("""
        - 📈 **Tendencias temporales**
        - 📊 **Distribuciones estadísticas**
        - 🔗 **Mapa de correlaciones**
        - 🎯 **Radar de hábitos**
        - 📅 **Comparativas temporales**
        """)

    st.markdown("---")

    # Configuración de análisis
    st.markdown("## ⚙️ Configuración")

    estrategia = st.selectbox(
        "Estrategia de imputación",
        ["auto", "zero", "mean", "forward_fill", "drop"],
        help="Cómo manejar datos faltantes"
    )

    incluir_tendencias = st.checkbox("Analizar tendencias", value=True)
    incluir_anomalias = st.checkbox("Detectar anomalías", value=True)

    st.markdown("---")
    st.markdown("""
    <div style='text-align: center; font-size: 0.8rem; opacity: 0.7;'>
        💡 Desarrollado con ❤️ por Fátima I.S<br>
        v1.0 - 2026
    </div>
    """, unsafe_allow_html=True)

# =============================================================================
# ZONA DE CARGA DE ARCHIVOS
# =============================================================================

st.markdown("### 📁 Carga tu Archivo de Hábitos")

col1, col2, col3 = st.columns([1, 2, 1])

with col2:
    uploaded_file = st.file_uploader(
        "",
        type=['csv', 'xlsx', 'xls', 'docx'],
        help="Arrastra tu archivo aquí o haz clic para seleccionar"
    )

# =============================================================================
# PROCESAMIENTO Y ANÁLISIS
# =============================================================================

if uploaded_file:
    try:
        # Mostrar spinner mientras se procesa
        with st.spinner('🔄 Cargando y procesando tu archivo...'):
            # Guardar archivo temporal
            temp_path = guardar_archivo_temporal(uploaded_file)

            # Cargar y limpiar datos
            df = cargar_y_limpiar_datos(temp_path, estrategia_imputacion=estrategia)

        st.success(f"✅ Archivo cargado exitosamente: **{len(df)} registros** encontrados")

        # =============================================================================
        # MÉTRICAS RÁPIDAS
        # =============================================================================

        st.markdown("---")
        st.markdown("### 📊 Vista General")

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric("📅 Total de Días", len(df))

        with col2:
            st.metric("📈 Hábitos Medidos", len(df.select_dtypes(include=['number']).columns))

        with col3:
            datos_completos = (df.notna().sum().sum() / df.size * 100)
            st.metric("✅ Datos Completos", f"{datos_completos:.1f}%")

        with col4:
            # Calcular rango de fechas si existe columna de fecha
            fecha_cols = [col for col in df.columns if pd.api.types.is_datetime64_any_dtype(df[col])]
            if fecha_cols:
                rango = (df[fecha_cols[0]].max() - df[fecha_cols[0]].min()).days
                st.metric("📆 Rango Temporal", f"{rango} días")
            else:
                st.metric("📆 Rango Temporal", "N/A")

        # =============================================================================
        # TABS PRINCIPALES
        # =============================================================================

        tab1, tab2, tab3, tab4 = st.tabs(["📋 Datos", "🚨 Alertas", "📊 Visualizaciones", "📈 Estadísticas"])

        # ==================== TAB 1: DATOS ====================
        with tab1:
            st.markdown("### 📋 Vista de Datos")

            col1, col2 = st.columns([3, 1])

            with col1:
                st.dataframe(df, use_container_width=True, height=400)

            with col2:
                st.markdown("#### 🔍 Info del Dataset")
                st.markdown(f"**Forma:** {df.shape[0]} × {df.shape[1]}")
                st.markdown(f"**Memoria:** {df.memory_usage(deep=True).sum() / 1024:.1f} KB")

                st.markdown("#### 📊 Tipos de Datos")
                tipos = df.dtypes.value_counts()
                for tipo, count in tipos.items():
                    st.markdown(f"- `{tipo}`: {count}")

                # Botón de descarga
                csv = df.to_csv(index=False).encode('utf-8')
                st.download_button(
                    "⬇️ Descargar CSV",
                    csv,
                    "datos_limpios.csv",
                    "text/csv",
                    key='download-csv'
                )

        # ==================== TAB 2: ALERTAS ====================
        with tab2:
            st.markdown("### 🚨 Alertas y Recomendaciones")

            with st.spinner('🔍 Analizando tus hábitos...'):
                resultado = analisis_completo(df)

            alertas = resultado['alertas']

            if len(alertas) == 0:
                st.success("🎉 ¡Excelente! No se encontraron alertas críticas. Tus hábitos están en buen camino.")
            else:
                # Separar alertas por severidad
                criticas = [a for a in alertas if a.severidad == SeveridadAlerta.CRITICO]
                advertencias = [a for a in alertas if a.severidad == SeveridadAlerta.ADVERTENCIA]
                positivas = [a for a in alertas if a.severidad == SeveridadAlerta.POSITIVO]
                info = [a for a in alertas if a.severidad == SeveridadAlerta.INFO]

                # Mostrar resumen
                col1, col2, col3, col4 = st.columns(4)
                with col1:
                    st.metric("🚨 Críticas", len(criticas))
                with col2:
                    st.metric("⚠️ Advertencias", len(advertencias))
                with col3:
                    st.metric("✅ Positivas", len(positivas))
                with col4:
                    st.metric("ℹ️ Info", len(info))

                st.markdown("---")

                # Mostrar alertas
                if criticas:
                    st.markdown("#### 🚨 Alertas Críticas")
                    for alerta in criticas:
                        mostrar_alerta(alerta)

                if advertencias:
                    st.markdown("#### ⚠️ Advertencias")
                    for alerta in advertencias:
                        mostrar_alerta(alerta)

                if positivas:
                    st.markdown("#### ✅ ¡Felicitaciones!")
                    for alerta in positivas:
                        mostrar_alerta(alerta)

                if info:
                    st.markdown("#### ℹ️ Información Adicional")
                    for alerta in info:
                        mostrar_alerta(alerta)

        # ==================== TAB 3: VISUALIZACIONES ====================
        with tab3:
            st.markdown("### 📊 Visualizaciones Interactivas")

            visualizacion = st.selectbox(
                "Selecciona el tipo de visualización",
                [
                    "🎯 Dashboard Completo",
                    "📈 Tendencias Temporales",
                    "📊 Distribuciones",
                    "🔗 Mapa de Correlaciones",
                    "🎯 Radar de Hábitos"
                ]
            )

            with st.spinner(f'🎨 Generando {visualizacion}...'):
                if visualizacion == "🎯 Dashboard Completo":
                    figuras = generar_dashboard_completo(df)

                    if len(figuras) > 0:
                        for i, fig in enumerate(figuras):
                            st.plotly_chart(fig, use_container_width=True)
                            if i < len(figuras) - 1:
                                st.markdown("---")
                    else:
                        st.warning("No se pudieron generar visualizaciones. Verifica que tus datos incluyan columnas numéricas.")

                elif visualizacion == "📈 Tendencias Temporales":
                    try:
                        fig = grafico_tendencias(df)
                        st.plotly_chart(fig, use_container_width=True)
                    except Exception as e:
                        st.error(f"Error al generar tendencias: {e}")

                elif visualizacion == "📊 Distribuciones":
                    try:
                        fig = grafico_distribuciones(df)
                        st.plotly_chart(fig, use_container_width=True)
                    except Exception as e:
                        st.error(f"Error al generar distribuciones: {e}")

                elif visualizacion == "🔗 Mapa de Correlaciones":
                    try:
                        fig = grafico_correlaciones(df)
                        st.plotly_chart(fig, use_container_width=True)

                        # Mostrar correlaciones en texto también
                        correlaciones = resultado['correlaciones']
                        if correlaciones:
                            st.markdown("#### 🔗 Correlaciones Significativas")
                            for hab1, hab2, corr in correlaciones[:5]:
                                if corr > 0:
                                    st.success(f"✅ **{hab1}** y **{hab2}** están positivamente correlacionados ({corr:.2f})")
                                else:
                                    st.error(f"❌ **{hab1}** y **{hab2}** están negativamente correlacionados ({corr:.2f})")
                    except Exception as e:
                        st.error(f"Error al generar correlaciones: {e}")

                elif visualizacion == "🎯 Radar de Hábitos":
                    try:
                        fig = grafico_radar_habitos(df, normalizar=True)
                        st.plotly_chart(fig, use_container_width=True)
                        st.info("💡 Este gráfico muestra tus hábitos normalizados en una escala de 0-100 para facilitar la comparación.")
                    except Exception as e:
                        st.error(f"Error al generar radar: {e}")

        # ==================== TAB 4: ESTADÍSTICAS ====================
        with tab4:
            st.markdown("### 📈 Análisis Estadístico Detallado")

            resumen = resultado['resumen_estadistico']

            st.markdown("#### 📊 Estadísticas Descriptivas")
            st.dataframe(resumen, use_container_width=True)

            st.markdown("---")

            col1, col2 = st.columns(2)

            with col1:
                st.markdown("#### 🔗 Top 5 Correlaciones")
                correlaciones = resultado['correlaciones']
                if correlaciones:
                    for i, (hab1, hab2, corr) in enumerate(correlaciones[:5], 1):
                        st.markdown(f"{i}. **{hab1}** ↔ **{hab2}**: `{corr:.3f}`")
                else:
                    st.info("No se encontraron correlaciones significativas")

            with col2:
                st.markdown("#### 📋 Resumen del Dataset")
                st.markdown(f"- **Total de días analizados:** {resultado['total_dias']}")
                st.markdown(f"- **Columnas analizadas:** {len(resultado['columnas_analizadas'])}")
                st.markdown(f"- **Alertas generadas:** {len(resultado['alertas'])}")

                # Calcular adherencia (% de datos no nulos)
                adherencia = (df.notna().sum().sum() / df.size * 100)
                st.markdown(f"- **Adherencia al registro:** {adherencia:.1f}%")

    except Exception as e:
        st.error(f"❌ Error al procesar el archivo: {str(e)}")
        st.info("💡 Asegúrate de que tu archivo cumple con los requisitos mencionados en la barra lateral.")

else:
    # =============================================================================
    # PANTALLA DE BIENVENIDA (cuando no hay archivo cargado)
    # =============================================================================

    st.markdown("---")

    col1, col2, col3 = st.columns([1, 2, 1])

    with col2:
        st.markdown("""
        <div style='text-align: center; padding: 3rem 0;'>
            <h2 style='color: #667eea; margin-bottom: 1rem;'>👋 ¡Bienvenido!</h2>
            <p style='font-size: 1.1rem; color: #666; margin-bottom: 2rem;'>
                Comienza subiendo tu archivo de hábitos diarios para obtener análisis instantáneos
            </p>

            <div style='background: rgba(102, 126, 234, 0.1); padding: 2rem; border-radius: 15px; margin: 2rem 0;'>
                <h3 style='color: #764ba2;'>✨ Características</h3>
                <ul style='text-align: left; display: inline-block; font-size: 1rem;'>
                    <li>📊 Análisis automático de hábitos</li>
                    <li>🚨 Alertas personalizadas</li>
                    <li>📈 Visualizaciones interactivas</li>
                    <li>🔗 Detección de correlaciones</li>
                    <li>📅 Seguimiento temporal</li>
                </ul>
            </div>
        </div>
        """, unsafe_allow_html=True)

        # Ejemplo de datos
        with st.expander("📋 Ver Ejemplo de Formato de Datos"):
            ejemplo_df = pd.DataFrame({
                'fecha': pd.date_range('2025-01-01', periods=7),
                'sueño_horas': [7.5, 6.0, 8.0, 7.0, 6.5, 8.5, 7.0],
                'ejercicio_min': [30, 20, 45, 0, 30, 60, 40],
                'agua_vasos': [8, 6, 9, 5, 7, 10, 8],
                'productividad': [8, 6, 9, 5, 7, 9, 8]
            })
            st.dataframe(ejemplo_df, use_container_width=True)
            st.info("💡 Este es un ejemplo de cómo debería estructurarse tu archivo")

# =============================================================================
# FOOTER
# =============================================================================

st.markdown("---")
st.markdown("""
<div style='text-align: center; color: #999; font-size: 0.9rem; padding: 1rem 0;'>
    <p>💡 <strong>Tip:</strong> Para mejores resultados, registra tus hábitos diariamente durante al menos 7 días</p>
    <p style='margin-top: 0.5rem;'>Desarrollado con Streamlit 🎈 | Datos procesados localmente 🔒</p>
</div>
""", unsafe_allow_html=True)
