# -*- coding: utf-8 -*-
"""data_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1schMTq9UHiTcj9Lyq4IqMldbDMzY_r2s
"""

# =============================================================================
# MÓDULO DE INGESTA Y LIMPIEZA DE DATOS (DATA INGESTION AND CLEANING)
# Optimizado para análisis de hábitos diarios
# =============================================================================

import pandas as pd
import numpy as np

try:
    from docx import Document
except ImportError:
    print("Advertencia: La librería 'python-docx' no está instalada. No se podrán cargar archivos .docx.")


# =============================================================================
# FUNCIONES DE CARGA DE ARCHIVOS
# =============================================================================

def _cargar_csv(ruta: str) -> pd.DataFrame:
    """Función auxiliar para cargar archivos CSV con detección automática de delimitadores."""
    try:
        # Intento 1: Motor rápido de C (coma como separador por defecto)
        return pd.read_csv(ruta, encoding='utf-8')
    except (pd.errors.ParserError, UnicodeDecodeError):
        try:
            # Intento 2: Detección automática de delimitadores (más lento pero robusto)
            return pd.read_csv(ruta, encoding='utf-8', sep=None, engine='python')
        except Exception:
            # Intento 3: Encoding alternativo (común en Windows)
            return pd.read_csv(ruta, encoding='latin-1', sep=None, engine='python')


def _cargar_excel(ruta: str) -> pd.DataFrame:
    """Función auxiliar para cargar archivos XLSX/XLS."""
    return pd.read_excel(ruta)


def _cargar_word(ruta: str) -> pd.DataFrame:
    """
    Función auxiliar para cargar la primera tabla de un archivo DOCX como DataFrame.
    Maneja robustamente la ausencia y el vacío de encabezados.
    """
    try:
        document = Document(ruta)
    except NameError:
        raise ImportError("La librería 'python-docx' no está disponible.")
    except Exception as e:
        raise IOError(f"Error al abrir el archivo Word: {e}")

    if not document.tables:
        raise ValueError(f"El archivo DOCX '{ruta.split('/')[-1]}' no contiene tablas.")

    tabla = document.tables[0]
    keys = [cell.text.strip() for cell in tabla.rows[0].cells]
    keys = [f'Columna_{i}' if not key else key for i, key in enumerate(keys)]
    data = [[cell.text.strip() for cell in row.cells] for row in tabla.rows[1:]]

    return pd.DataFrame(data, columns=keys)


# =============================================================================
# DETECCIÓN INTELIGENTE DE TIPOS DE COLUMNAS
# =============================================================================

def _detectar_tipo_columna(df: pd.DataFrame, col: str) -> str:
    """
    Detecta inteligentemente el tipo de columna para aplicar la estrategia correcta.

    Returns:
        'fecha', 'numerica_habito', 'numerica_metrica', 'categorica'
    """
    col_lower = col.lower()

    # 1. Detectar columnas de fecha
    if any(keyword in col_lower for keyword in ['fecha', 'date', 'dia', 'day', 'timestamp']):
        return 'fecha'

    # 2. Detectar hábitos cuantificables (NaN debería ser 0)
    habitos_zero = [
        'ejercicio', 'pasos', 'steps', 'agua', 'water', 'calorias', 'calories',
        'horas', 'hours', 'minutos', 'minutes', 'vasos', 'glasses', 'km',
        'repeticiones', 'reps', 'series', 'sets', 'cigarrillos', 'cigarettes'
    ]
    if any(keyword in col_lower for keyword in habitos_zero):
        return 'numerica_habito'

    # 3. Detectar métricas continuas (NaN debería propagarse del valor anterior)
    metricas_continuas = [
        'peso', 'weight', 'masa', 'altura', 'height', 'imc', 'bmi',
        'temperatura', 'temp', 'presion', 'pressure', 'glucosa', 'glucose'
    ]
    if any(keyword in col_lower for keyword in metricas_continuas):
        return 'numerica_metrica'

    # 4. Por defecto, categórica
    return 'categorica'


def _convertir_tipos_inteligente(df: pd.DataFrame) -> pd.DataFrame:
    """
    Convierte tipos de datos de forma inteligente sin convertir TODO a numérico.

    Solo convierte columnas que realmente parecen numéricas.
    """
    df_convertido = df.copy()

    for col in df_convertido.columns:
        tipo = _detectar_tipo_columna(df_convertido, col)

        if tipo == 'fecha':
            # Convertir a datetime
            df_convertido[col] = pd.to_datetime(df_convertido[col], errors='coerce')

        elif tipo in ['numerica_habito', 'numerica_metrica']:
            # Convertir a numérico
            df_convertido[col] = pd.to_numeric(df_convertido[col], errors='coerce')

        # Las categóricas se mantienen como object (no hacemos nada)

    return df_convertido


# =============================================================================
# IMPUTACIÓN INTELIGENTE CON ESTRATEGIAS
# =============================================================================

def imputacion_inteligente(df: pd.DataFrame, estrategia_global: str = 'auto') -> pd.DataFrame:
    """
    Maneja NaNs de forma inteligente según el tipo de columna.

    Args:
        df: DataFrame de entrada
        estrategia_global:
            - 'auto' (RECOMENDADO): Aplica la mejor estrategia según el tipo de columna
            - 'zero': Rellena todo con 0 (numéricos) o 'No registrado' (categóricos)
            - 'mean': Rellena con media/moda (tu código original)
            - 'forward_fill': Propaga el último valor válido
            - 'drop': Elimina filas con NaN

    Returns:
        DataFrame limpio
    """
    df_limpio = df.copy()

    # 1. Convertir tipos de forma inteligente
    df_limpio = _convertir_tipos_inteligente(df_limpio)

    # 2. Aplicar estrategia
    if estrategia_global == 'auto':
        # 🔥 MODO AUTOMÁTICO: La mejor opción para hábitos diarios
        for col in df_limpio.columns:
            tipo = _detectar_tipo_columna(df_limpio, col)

            if tipo == 'fecha':
                # Las fechas no se imputan, se mantienen como NaT si faltan
                pass

            elif tipo == 'numerica_habito':
                # Hábitos cuantificables: NaN = no se realizó la actividad
                df_limpio[col] = df_limpio[col].fillna(0)

            elif tipo == 'numerica_metrica':
                # Métricas continuas: propagar el último valor válido
                df_limpio[col].fillna(method='ffill', inplace=True)

            elif tipo == 'categorica':
                # Categóricas: rellenar con 'No registrado'
                df_limpio[col].fillna('No registrado', inplace=True)

    elif estrategia_global == 'zero':
        columnas_numericas = df_limpio.select_dtypes(include=[np.number]).columns
        df_limpio[columnas_numericas] = df_limpio[columnas_numericas].fillna(0)

        columnas_categoricas = df_limpio.select_dtypes(include=['object']).columns
        for col in columnas_categoricas:
            df_limpio[col].fillna('No registrado', inplace=True)

    elif estrategia_global == 'mean':
        # Tu código original
        columnas_numericas = df_limpio.select_dtypes(include=[np.number]).columns
        medias_validas = df_limpio[columnas_numericas].mean().dropna()
        df_limpio[columnas_numericas] = df_limpio[columnas_numericas].fillna(medias_validas)

        columnas_categoricas = df_limpio.select_dtypes(include=['object']).columns
        for col in columnas_categoricas:
            moda_serie = df_limpio[col].mode()
            if not moda_serie.empty:
                df_limpio[col].fillna(moda_serie.iloc[0], inplace=True)

    elif estrategia_global == 'forward_fill':
        df_limpio = df_limpio.fillna(method='ffill')

    elif estrategia_global == 'drop':
        df_limpio = df_limpio.dropna()

    else:
        raise ValueError(f"Estrategia '{estrategia_global}' no válida. Usa: 'auto', 'zero', 'mean', 'forward_fill', 'drop'")

    # 3. Eliminar columnas 100% vacías
    df_limpio.dropna(axis=1, how='all', inplace=True)

    return df_limpio


# =============================================================================
# VALIDACIONES ESPECÍFICAS PARA HÁBITOS DIARIOS
# =============================================================================

def _validar_estructura_habitos(df: pd.DataFrame) -> None:
    """
    Valida que el DataFrame tenga una estructura válida para análisis de hábitos.
    Lanza advertencias si falta información crítica.
    """
    # Buscar columna de fecha
    columnas_fecha = [col for col in df.columns if _detectar_tipo_columna(df, col) == 'fecha']

    if not columnas_fecha:
        print("⚠️  ADVERTENCIA: No se detectó una columna de fecha. Considera añadir 'Fecha' para análisis temporal.")
    else:
        print(f"✅ Columna de fecha detectada: '{columnas_fecha[0]}'")

    # Verificar si hay suficientes filas para análisis
    if len(df) < 7:
        print(f"⚠️  ADVERTENCIA: Solo hay {len(df)} filas. Se recomienda al menos 7 días para análisis significativos.")


def _ordenar_por_fecha(df: pd.DataFrame) -> pd.DataFrame:
    """
    Ordena el DataFrame por fecha si existe una columna de fecha.
    También elimina duplicados de fecha manteniendo el registro más reciente.
    """
    df_ordenado = df.copy()

    # Buscar columna de fecha
    columnas_fecha = [col for col in df_ordenado.columns if _detectar_tipo_columna(df_ordenado, col) == 'fecha']

    if columnas_fecha:
        col_fecha = columnas_fecha[0]

        # Eliminar duplicados por fecha (mantener el último registro)
        duplicados_antes = len(df_ordenado)
        df_ordenado = df_ordenado.drop_duplicates(subset=[col_fecha], keep='last')
        duplicados_despues = len(df_ordenado)

        if duplicados_antes != duplicados_despues:
            print(f"🔄 Se eliminaron {duplicados_antes - duplicados_despues} registros duplicados por fecha.")

        # Ordenar por fecha
        df_ordenado = df_ordenado.sort_values(by=col_fecha).reset_index(drop=True)
        print(f"📅 Datos ordenados por fecha ({col_fecha})")

    return df_ordenado


# =============================================================================
# FUNCIÓN PRINCIPAL
# =============================================================================

def cargar_y_limpiar_datos(ruta: str, estrategia_imputacion: str = 'auto') -> pd.DataFrame:
    """
    Función principal que carga un archivo y aplica limpieza optimizada para hábitos diarios.

    Args:
        ruta: Ruta del archivo (.csv, .xlsx, .xls, .docx)
        estrategia_imputacion:
            - 'auto' (RECOMENDADO): Detecta automáticamente la mejor estrategia por columna
            - 'zero': NaN = 0 para numéricos, 'No registrado' para categóricos
            - 'mean': NaN = media/moda (imputación estadística)
            - 'forward_fill': Propagar último valor válido
            - 'drop': Eliminar filas con NaN

    Returns:
        DataFrame limpio y listo para análisis

    Ejemplo:
        >>> df = cargar_y_limpiar_datos('habitos.csv')  # Usa 'auto' por defecto
        >>> df = cargar_y_limpiar_datos('habitos.xlsx', estrategia_imputacion='zero')
    """
    ruta_original = ruta
    ruta = ruta.lower()

    try:
        # ==================== PASO 1: CARGA ====================
        if ruta.endswith(('.csv', '.txt')):
            df = _cargar_csv(ruta_original)
        elif ruta.endswith(('.xlsx', '.xls')):
            df = _cargar_excel(ruta_original)
        elif ruta.endswith('.docx'):
            df = _cargar_word(ruta_original)
        else:
            raise ValueError("Formato de archivo no soportado. Por favor, usa .csv, .xlsx, .xls o .docx.")

        print(f"✅ Archivo '{ruta_original.split('/')[-1]}' cargado correctamente (Filas: {len(df)}, Columnas: {len(df.columns)})")

        # ==================== PASO 2: VALIDACIÓN ====================
        _validar_estructura_habitos(df)

        # ==================== PASO 3: LIMPIEZA E IMPUTACIÓN ====================
        df_limpio = imputacion_inteligente(df, estrategia_global=estrategia_imputacion)

        print(f"✨ Datos limpiados con estrategia '{estrategia_imputacion}'. Columnas restantes: {len(df_limpio.columns)}")

        # ==================== PASO 4: ORDENAMIENTO Y POST-PROCESAMIENTO ====================
        df_limpio = _ordenar_por_fecha(df_limpio)

        print(f"🎯 DataFrame listo para análisis. Forma final: {df_limpio.shape}")

        return df_limpio

    except Exception as e:
        print(f"❌ ERROR FATAL en el proceso de ingesta/limpieza: {e}")
        raise  # Propagamos el error en lugar de retornar DataFrame vacío


# =============================================================================
# FUNCIÓN AUTOMATICA ROBUSTA
# =============================================================================

def imputacion_automatica_robusta(df: pd.DataFrame) -> pd.DataFrame:
    """
    FUNCIÓN LEGACY: Mantiene compatibilidad con tu código anterior.
    Usa 'mean' como estrategia por defecto.

    ⚠️ RECOMENDACIÓN: Usa imputacion_inteligente() con estrategia='auto' en su lugar.
    """
    print("⚠️  Usando función legacy. Considera migrar a imputacion_inteligente() con estrategia='auto'")
    return imputacion_inteligente(df, estrategia_global='mean')

