# -*- coding: utf-8 -*-
"""plot_utils ( con explicaciones).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8fHXZJLTgRr8cCMGhUVLi62Gy9qxyaX
"""

# =============================================================================
# MÓDULO DE VISUALIZACIÓN AVANZADO (PLOT UTILS)
# =============================================================================

import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from typing import List, Optional, Dict, Tuple
import warnings

warnings.filterwarnings('ignore')


# =============================================================================
# CONFIGURACIÓN DE COLORES Y ESTILOS
# =============================================================================

COLORES_POSITIVOS = ['#10b981', '#34d399', '#6ee7b7']  # Verdes
COLORES_NEGATIVOS = ['#ef4444', '#f87171', '#fca5a5']  # Rojos
COLORES_NEUTROS = ['#3b82f6', '#60a5fa', '#93c5fd']    # Azules
COLORES_ADVERTENCIA = ['#f59e0b', '#fbbf24', '#fcd34d'] # Amarillos

TEMPLATE = 'plotly_white'  # Tema limpio y profesional


# =============================================================================
# DETECCIÓN AUTOMÁTICA DE COLUMNA DE FECHA
# =============================================================================

def _detectar_columna_fecha(df: pd.DataFrame) -> Optional[str]:
    """Detecta automáticamente la columna de fecha en el DataFrame."""
    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            return col
        # Intentar detectar por nombre
        if any(keyword in col.lower() for keyword in ['fecha', 'date', 'dia', 'day', 'timestamp']):
            return col
    return None


def _detectar_tipo_habito(nombre_col: str) -> str:
    """
    Clasifica el hábito para asignar colores apropiados.
    Returns: 'positivo', 'negativo', 'neutro'
    """
    nombre_lower = nombre_col.lower()

    # Hábitos positivos (más es mejor)
    positivos = ['ejercicio', 'exercise', 'pasos', 'steps', 'agua', 'water',
                 'sueño', 'sleep', 'productividad', 'productivity']

    # Hábitos negativos (menos es mejor)
    negativos = ['cigarrillos', 'cigarettes', 'alcohol', 'pantalla', 'screen',
                 'procrastinacion', 'procrastination', 'estres', 'stress']

    if any(palabra in nombre_lower for palabra in positivos):
        return 'positivo'
    elif any(palabra in nombre_lower for palabra in negativos):
        return 'negativo'
    else:
        return 'neutro'


# =============================================================================
# GRÁFICO 1: TENDENCIAS TEMPORALES
# =============================================================================

def grafico_tendencias(df: pd.DataFrame, columnas: Optional[List[str]] = None) -> go.Figure:
    """
    Genera un gráfico de líneas con las tendencias temporales de los hábitos.

    Args:
        df: DataFrame con datos de hábitos
        columnas: Lista de columnas a graficar. Si None, usa todas las numéricas

    Returns:
        Figura de Plotly con las tendencias
    """
    col_fecha = _detectar_columna_fecha(df)

    if col_fecha is None:
        raise ValueError("No se encontró una columna de fecha en el DataFrame")

    # Si no se especifican columnas, usar todas las numéricas
    if columnas is None:
        columnas = df.select_dtypes(include=[np.number]).columns.tolist()

    # Crear figura con subplots
    fig = make_subplots(
        rows=len(columnas),
        cols=1,
        subplot_titles=[col.replace('_', ' ').title() for col in columnas],
        vertical_spacing=0.05
    )

    # Añadir una línea por cada hábito
    for i, col in enumerate(columnas, 1):
        tipo = _detectar_tipo_habito(col)

        if tipo == 'positivo':
            color = COLORES_POSITIVOS[0]
        elif tipo == 'negativo':
            color = COLORES_NEGATIVOS[0]
        else:
            color = COLORES_NEUTROS[0]

        fig.add_trace(
            go.Scatter(
                x=df[col_fecha],
                y=df[col],
                mode='lines+markers',
                name=col.replace('_', ' ').title(),
                line=dict(color=color, width=2),
                marker=dict(size=6),
                hovertemplate='<b>%{x|%d/%m/%Y}</b><br>Valor: %{y:.1f}<extra></extra>'
            ),
            row=i, col=1
        )

        # Añadir línea de promedio
        promedio = df[col].mean()
        fig.add_hline(
            y=promedio,
            line_dash="dash",
            line_color="gray",
            opacity=0.5,
            row=i, col=1
        )

    fig.update_layout(
        height=300 * len(columnas),
        title_text="📈 Evolución de Hábitos en el Tiempo",
        showlegend=False,
        template=TEMPLATE,
        hovermode='x unified'
    )

    fig.update_xaxes(title_text="Fecha")
    fig.update_yaxes(title_text="Valor")

    return fig


# =============================================================================
# GRÁFICO 2: DISTRIBUCIONES (HISTOGRAMAS + BOX PLOTS)
# =============================================================================

def grafico_distribuciones(df: pd.DataFrame, columnas: Optional[List[str]] = None) -> go.Figure:
    """
    Genera histogramas y box plots para ver la distribución de cada hábito.

    Args:
        df: DataFrame con datos de hábitos
        columnas: Lista de columnas a graficar. Si None, usa todas las numéricas

    Returns:
        Figura de Plotly con las distribuciones
    """
    if columnas is None:
        columnas = df.select_dtypes(include=[np.number]).columns.tolist()

    # Crear subplots: una fila por columna, 2 columnas (histograma + boxplot)
    fig = make_subplots(
        rows=len(columnas),
        cols=2,
        subplot_titles=[item for col in columnas for item in [f'Distribución: {col}', f'Box Plot: {col}']],
        column_widths=[0.7, 0.3],
        vertical_spacing=0.08,
        horizontal_spacing=0.1
    )

    for i, col in enumerate(columnas, 1):
        tipo = _detectar_tipo_habito(col)

        if tipo == 'positivo':
            color = COLORES_POSITIVOS[0]
        elif tipo == 'negativo':
            color = COLORES_NEGATIVOS[0]
        else:
            color = COLORES_NEUTROS[0]

        # Histograma
        fig.add_trace(
            go.Histogram(
                x=df[col],
                name=col,
                marker_color=color,
                opacity=0.7,
                showlegend=False,
                hovertemplate='Rango: %{x}<br>Frecuencia: %{y}<extra></extra>'
            ),
            row=i, col=1
        )

        # Box plot
        fig.add_trace(
            go.Box(
                y=df[col],
                name=col,
                marker_color=color,
                showlegend=False,
                boxmean='sd',  # Mostrar media y desviación estándar
                hovertemplate='<b>Estadísticas</b><br>Valor: %{y:.1f}<extra></extra>'
            ),
            row=i, col=2
        )

    fig.update_layout(
        height=250 * len(columnas),
        title_text="📊 Distribución de Hábitos",
        template=TEMPLATE
    )

    return fig


# =============================================================================
# GRÁFICO 3: HEATMAP DE CORRELACIONES
# =============================================================================

def grafico_correlaciones(df: pd.DataFrame) -> go.Figure:
    """
    Genera un heatmap de correlaciones entre todos los hábitos.

    Args:
        df: DataFrame con datos de hábitos

    Returns:
        Figura de Plotly con el heatmap
    """
    df_numerico = df.select_dtypes(include=[np.number])

    if len(df_numerico.columns) < 2:
        raise ValueError("Se necesitan al menos 2 columnas numéricas para calcular correlaciones")

    # Calcular matriz de correlación
    corr_matrix = df_numerico.corr()

    # Crear heatmap
    fig = go.Figure(data=go.Heatmap(
        z=corr_matrix.values,
        x=[col.replace('_', ' ').title() for col in corr_matrix.columns],
        y=[col.replace('_', ' ').title() for col in corr_matrix.columns],
        colorscale='RdBu',
        zmid=0,
        text=corr_matrix.values.round(2),
        texttemplate='%{text}',
        textfont={"size": 10},
        colorbar=dict(title="Correlación"),
        hovertemplate='%{x} vs %{y}<br>Correlación: %{z:.2f}<extra></extra>'
    ))

    fig.update_layout(
        title="🔗 Mapa de Correlaciones entre Hábitos",
        height=600,
        template=TEMPLATE,
        xaxis={'side': 'bottom'},
        yaxis={'side': 'left'}
    )

    return fig


# =============================================================================
# GRÁFICO 4: COMPARATIVA SEMANAL/MENSUAL
# =============================================================================

def grafico_comparativa_temporal(
    df: pd.DataFrame,
    columna: str,
    frecuencia: str = 'W'
) -> go.Figure:
    """
    Compara promedios por semana o mes.

    Args:
        df: DataFrame con datos de hábitos
        columna: Columna a analizar
        frecuencia: 'W' para semanal, 'M' para mensual

    Returns:
        Figura de Plotly con la comparativa
    """
    col_fecha = _detectar_columna_fecha(df)

    if col_fecha is None:
        raise ValueError("No se encontró una columna de fecha")

    # Agrupar por período
    df_temp = df.copy()
    df_temp[col_fecha] = pd.to_datetime(df_temp[col_fecha])
    df_temp = df_temp.set_index(col_fecha)

    if frecuencia == 'W':
        agrupado = df_temp[columna].resample('W').mean()
        titulo_periodo = "Semana"
    else:
        agrupado = df_temp[columna].resample('M').mean()
        titulo_periodo = "Mes"

    tipo = _detectar_tipo_habito(columna)
    color = COLORES_POSITIVOS[0] if tipo == 'positivo' else COLORES_NEUTROS[0]

    fig = go.Figure()

    # Barras
    fig.add_trace(go.Bar(
        x=agrupado.index,
        y=agrupado.values,
        marker_color=color,
        name=columna,
        hovertemplate='<b>%{x|%d/%m/%Y}</b><br>Promedio: %{y:.1f}<extra></extra>'
    ))

    # Línea de tendencia
    fig.add_trace(go.Scatter(
        x=agrupado.index,
        y=agrupado.values,
        mode='lines',
        line=dict(color='red', width=2, dash='dash'),
        name='Tendencia',
        hoverinfo='skip'
    ))

    fig.update_layout(
        title=f"📅 Promedio {titulo_periodo.lower()}al de {columna.replace('_', ' ').title()}",
        xaxis_title=titulo_periodo,
        yaxis_title="Promedio",
        template=TEMPLATE,
        height=400,
        showlegend=True
    )

    return fig


# =============================================================================
# GRÁFICO 5: RADAR CHART (RESUMEN GLOBAL)
# =============================================================================

def grafico_radar_habitos(df: pd.DataFrame, normalizar: bool = True) -> go.Figure:
    """
    Genera un gráfico de radar con el promedio de todos los hábitos.
    Útil para ver de un vistazo qué áreas están mejor/peor.

    Args:
        df: DataFrame con datos de hábitos
        normalizar: Si True, normaliza los valores entre 0-100

    Returns:
        Figura de Plotly con el radar chart
    """
    df_numerico = df.select_dtypes(include=[np.number])

    # Calcular promedios
    promedios = df_numerico.mean()

    if normalizar:
        # Normalizar a escala 0-100
        valores = ((promedios - promedios.min()) / (promedios.max() - promedios.min()) * 100).values
    else:
        valores = promedios.values

    categorias = [col.replace('_', ' ').title() for col in promedios.index]

    fig = go.Figure()

    fig.add_trace(go.Scatterpolar(
        r=valores,
        theta=categorias,
        fill='toself',
        name='Promedio',
        line_color=COLORES_NEUTROS[0],
        fillcolor=COLORES_NEUTROS[0],
        opacity=0.6,
        hovertemplate='<b>%{theta}</b><br>Valor: %{r:.1f}<extra></extra>'
    ))

    fig.update_layout(
        polar=dict(
            radialaxis=dict(
                visible=True,
                range=[0, 100] if normalizar else [0, max(valores) * 1.1]
            )
        ),
        title="🎯 Radar de Hábitos (Promedio General)",
        template=TEMPLATE,
        height=500
    )

    return fig


# =============================================================================
# GRÁFICO 6: CALENDARIO DE CALOR (HEATMAP TEMPORAL)
# =============================================================================

def grafico_calendario(df: pd.DataFrame, columna: str) -> go.Figure:
    """
    Genera un calendario de calor mostrando el valor de un hábito cada día.
    Similar al contribution graph de GitHub.

    Args:
        df: DataFrame con datos de hábitos
        columna: Columna a visualizar

    Returns:
        Figura de Plotly con el calendario
    """
    col_fecha = _detectar_columna_fecha(df)

    if col_fecha is None:
        raise ValueError("No se encontró una columna de fecha")

    df_temp = df.copy()
    df_temp[col_fecha] = pd.to_datetime(df_temp[col_fecha])

    # Añadir información de día de la semana y semana del año
    df_temp['dia_semana'] = df_temp[col_fecha].dt.dayofweek
    df_temp['semana'] = df_temp[col_fecha].dt.isocalendar().week

    # Crear matriz para el heatmap
    pivot = df_temp.pivot_table(
        values=columna,
        index='dia_semana',
        columns='semana',
        aggfunc='mean'
    )

    dias = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom']

    tipo = _detectar_tipo_habito(columna)

    if tipo == 'positivo':
        colorscale = 'Greens'
    elif tipo == 'negativo':
        colorscale = 'Reds'
    else:
        colorscale = 'Blues'

    fig = go.Figure(data=go.Heatmap(
        z=pivot.values,
        x=pivot.columns,
        y=dias,
        colorscale=colorscale,
        hovertemplate='Semana %{x}<br>%{y}<br>Valor: %{z:.1f}<extra></extra>',
        colorbar=dict(title="Valor")
    ))

    fig.update_layout(
        title=f"📆 Calendario de {columna.replace('_', ' ').title()}",
        xaxis_title="Semana del año",
        yaxis_title="Día de la semana",
        template=TEMPLATE,
        height=400
    )

    return fig


# =============================================================================
# FUNCIÓN PARA GENERAR DASHBOARD COMPLETO
# =============================================================================

def generar_dashboard_completo(df: pd.DataFrame, guardar_html: bool = False) -> List[go.Figure]:
    """
    Genera todas las visualizaciones automáticamente.

    Args:
        df: DataFrame con datos de hábitos
        guardar_html: Si True, guarda cada gráfico como HTML

    Returns:
        Lista con todas las figuras generadas
    """
    figuras = []
    columnas_numericas = df.select_dtypes(include=[np.number]).columns.tolist()

    print("🎨 Generando visualizaciones...")

    try:
        # 1. Tendencias temporales
        print("   📈 Gráfico de tendencias...")
        fig1 = grafico_tendencias(df)
        figuras.append(fig1)
        if guardar_html:
            fig1.write_html("tendencias.html")
    except Exception as e:
        print(f"   ⚠️ No se pudo generar tendencias: {e}")

    try:
        # 2. Distribuciones
        print("   📊 Gráfico de distribuciones...")
        fig2 = grafico_distribuciones(df)
        figuras.append(fig2)
        if guardar_html:
            fig2.write_html("distribuciones.html")
    except Exception as e:
        print(f"   ⚠️ No se pudo generar distribuciones: {e}")

    try:
        # 3. Correlaciones
        if len(columnas_numericas) >= 2:
            print("   🔗 Heatmap de correlaciones...")
            fig3 = grafico_correlaciones(df)
            figuras.append(fig3)
            if guardar_html:
                fig3.write_html("correlaciones.html")
    except Exception as e:
        print(f"   ⚠️ No se pudo generar correlaciones: {e}")

    try:
        # 4. Radar de hábitos
        print("   🎯 Radar de hábitos...")
        fig4 = grafico_radar_habitos(df)
        figuras.append(fig4)
        if guardar_html:
            fig4.write_html("radar.html")
    except Exception as e:
        print(f"   ⚠️ No se pudo generar radar: {e}")

    try:
        # 5. Comparativa temporal (para la primera columna numérica)
        if len(columnas_numericas) > 0:
            print("   📅 Comparativa semanal...")
            fig5 = grafico_comparativa_temporal(df, columnas_numericas[0])
            figuras.append(fig5)
            if guardar_html:
                fig5.write_html("comparativa.html")
    except Exception as e:
        print(f"   ⚠️ No se pudo generar comparativa: {e}")

    print(f"✅ Se generaron {len(figuras)} visualizaciones")

    return figuras


# =============================================================================
# FUNCIONES LEGACY (COMPATIBILIDAD CON TU CÓDIGO ANTERIOR)
# =============================================================================

def grafico_interactivo(df: pd.DataFrame) -> Optional[go.Figure]:
    """
    Función legacy compatible con tu código anterior.
    Ahora genera un scatter plot mejorado.
    """
    print("⚠️ Usando función legacy. Considera usar generar_dashboard_completo()")

    columnas_necesarias = ['sueño_horas', 'estudio_horas', 'ejercicio_min', 'productividad']

    if not set(columnas_necesarias).issubset(df.columns):
        return None

    fig = px.scatter(
        df,
        x="sueño_horas",
        y="productividad",
        size="ejercicio_min",
        color="estudio_horas",
        title="Relación hábitos y productividad",
        labels={
            'sueño_horas': 'Horas de Sueño',
            'productividad': 'Productividad',
            'ejercicio_min': 'Minutos de Ejercicio',
            'estudio_horas': 'Horas de Estudio'
        },
        template=TEMPLATE
    )

    return fig


def pairplot_estatico(df: pd.DataFrame):
    """
    Función legacy. Ahora usa Plotly en lugar de Seaborn.
    """
    print("⚠️ pairplot_estatico está deprecado. Usa grafico_correlaciones() o grafico_distribuciones()")
    fig = grafico_correlaciones(df)
    fig.show()
